doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '9.6'
        charset: utf8

        url: '%env(resolve:DATABASE_URL)%'

        types:
            array_collection: 'ParkManager\Infrastructure\Doctrine\Type\ArrayCollectionType'
            park_manager_user_id: 'ParkManager\Infrastructure\Doctrine\Type\UserIdType'
            #park_manager_domain_id: 'ParkManager\Infrastructure\Doctrine\Type\DomainIdType' # Don't initiate this

            # Webhosting
            byte_size: 'ParkManager\Infrastructure\Doctrine\Type\ByteSizeType'
            park_manager_webhosting_space_id: 'ParkManager\Infrastructure\Doctrine\Type\WebhostingSpaceIdType'
            park_manager_webhosting_constraints_set_id: 'ParkManager\Infrastructure\Doctrine\Type\WebhostingConstraintSetIdType'
            park_manager_domain_name_id: 'ParkManager\Infrastructure\Doctrine\Type\DomainNameIdType'
            park_manager_sub_domain_id: 'ParkManager\Infrastructure\Doctrine\Type\SubDomainNameIdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'ParkManager\Domain'
                alias: ParkManager
            SecurityMapping:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/SecurityMapping'
                prefix: 'Rollerworks\Component\SplitToken'
