framework:
    messenger:
        default_bus: park_manager.command_bus
        buses:
            park_manager.command_bus:
                middleware:
                    - validation
                    - doctrine_transaction
            park_manager.event_bus:
                default_middleware: allow_no_handlers
            park_manager.query_bus:
#                middleware:
