framework:
    messenger:
        default_bus: park_manager.command_bus
        buses:
            park_manager.command_bus:
                middleware:
                    - validation
                    - doctrine_transaction
