security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        'ParkManager\Infrastructure\Security\AdministratorUser':
            algorithm: auto
        'ParkManager\Infrastructure\Security\User':
            algorithm: auto

    providers:
        in_memory: { memory: ~ }
        administrator: { id: 'park_manager.security.user_provider.administrator' }
        user: { id: 'park_manager.security.user_provider.user_user' }
        api: { id: 'park_manager.security.user_provider.user_user' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: '^/admin/'
            provider: administrator
            context: admin
            anonymous: true

            logout:
                csrf_parameter:       _csrf_token
                csrf_token_generator: security.csrf.token_manager
                csrf_token_id:        logout_admin
                path:                 '/admin/logout'
                target:               '/admin/'
            guard:
                authenticators:
                    - park_manager.security.guard.form.administrator

            remember_me:
                secret:               '%env(APP_SECRET)%'
                token_provider:       ~
                catch_exceptions:     true
                name:                 ADMIN_REMEMBERME
                lifetime:             604800 # one week
                path:                 admin/
                secure:               true
                httponly:             true
                always_remember_me:   false

        api:
            pattern: '^/api/'
            provider: api
            anonymous: false
            stateless: true

            http_basic: ~ # XXX Needs a custom guard and user for split-token with hex-encoded

        client:
            pattern: '^/'
            provider: user
            anonymous: true

            logout:
                csrf_parameter:       _csrf_token
                csrf_token_generator: security.csrf.token_manager
                csrf_token_id:        logout_client
                path:                 '/logout'
                target:               '/'
            guard:
                authenticators:
                    - park_manager.security.guard.form.user

            remember_me:
                secret:               '%env(APP_SECRET)%'
                token_provider:       ~
                catch_exceptions:     true
                name:                 CLIENT_REMEMBERME
                lifetime:             604800 # one week
                path:                 /
                secure:               true
                httponly:             true
                always_remember_me:   false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Admin
        - { path: '^/admin/login$', requires_channel: https, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin/password-reset/confirm', requires_channel: https, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin/', requires_channel: https, role: ROLE_ADMIN }

        # Client
        - { path: '^/login$', requires_channel: https, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/password-reset', requires_channel: https, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', requires_channel: https, role: ROLE_USER }
