# The routing system of Park-Manager uses the Rollerworks RouteAutowiringBundle
# To register routing information into slot. See https://github.com/rollerworks/RouteAutowiringBundle

# On top of that the Rollerworks ParkManagerCoreBundle provides the section specific loading
# of routing information from an autowired routing-slot.
#
# Avoid registering routes here directly but instead use the RouteAutowiringBundle
# and/or Symfony Flex to ensure bundle removal doesn't break the application.

_park_manager:
    type: park_manager_sections_loader
    resource: .
